# Auto-Merge pre to main
#
# Triggered on push to pre branch.
# Fast-forwards main to pre (no unit tests - e2e only).
# Migrated from GitHub Actions to save ubuntu-latest minutes.

when:
  - event: push
    branch: pre

steps:
  # No unit tests - only e2e tests available (Playwright)
  # E2E tests run separately, not blocking merge

  # Step 1: Fast-forward main to pre (Python script)
  - name: fast-forward-main
    image: bash
    commands:
      - cd "${CI_WORKSPACE}"
      - git config user.name "woodpecker-ci[bot]"
      - git config user.email "woodpecker-ci[bot]@users.noreply.github.com"
      - /opt/homebrew/bin/python3.12 /Users/christophvarga/bin/woodpecker-git-push-py "${CI_REPO}"
