# Deploy Trigger - Triggers central deploy pipeline in infra repo
#
# Flow: push to main -> trigger infra edge-deploy-on-push pipeline
#
# Required Secrets (set in Woodpecker for this repo):
#   - woodpecker_api_token (token with pipeline create permission)
#   - cf_access_client_id (Cloudflare Access Service Token)
#   - cf_access_client_secret (Cloudflare Access Service Token)
#
# IMPORTANT: Secret env vars MUST use $${VAR} (double dollar) in commands!
# Woodpecker pre-processes ${VAR} before shell execution.
# Only CI variables (${CI_COMMIT_BRANCH} etc.) use single ${}.

when:
  - event: push
    branch:
      - main

steps:
  - name: trigger-deploy
    image: bash
    environment:
      WOODPECKER_API_TOKEN:
        from_secret: woodpecker_api_token
      CF_ACCESS_CLIENT_ID:
        from_secret: cf_access_client_id
      CF_ACCESS_CLIENT_SECRET:
        from_secret: cf_access_client_secret
    commands:
      - |
        echo "=== Deploy Trigger ==="
        echo "App: qr"
        echo "Branch: ${CI_COMMIT_BRANCH}"
        echo "Commit: ${CI_COMMIT_SHA}"

        ENVIRONMENT="prod"

        HTTP_CODE=$(curl -s -o /tmp/deploy-response.json -w "%{http_code}" \
          -X POST "https://ci.varga.media/api/repos/1/pipelines" \
          -H "Authorization: Bearer $${WOODPECKER_API_TOKEN}" \
          -H "CF-Access-Client-Id: $${CF_ACCESS_CLIENT_ID}" \
          -H "CF-Access-Client-Secret: $${CF_ACCESS_CLIENT_SECRET}" \
          -H "Content-Type: application/json" \
          -d "{
            \"branch\": \"main\",
            \"variables\": {
              \"APP_NAME\": \"qr\",
              \"DEPLOY_BRANCH\": \"${CI_COMMIT_BRANCH}\",
              \"ENVIRONMENT\": \"$${ENVIRONMENT}\"
            }
          }")

        if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
          PIPELINE_NUM=$(cat /tmp/deploy-response.json | python3 -c "import json,sys; print(json.load(sys.stdin).get('number','?'))" 2>/dev/null || echo "?")
          echo "Deploy pipeline triggered! (Pipeline #$${PIPELINE_NUM})"
        else
          echo "ERROR: Failed to trigger deploy (HTTP $HTTP_CODE)"
          cat /tmp/deploy-response.json 2>/dev/null
          exit 1
        fi
